apiVersion: v1
kind: pod
metadata:
  name: label-demo
  labels:
    project: expense
    module: shipping
    environment: dev
specs:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
      - containerPort: 8080