apiVersion: v1
kind: pod
metadata:
  name: my-app
  labels:
    app: frontend
  annotations:
    description: "This pod runs the frontend service for the ecommerce app"
    owner: "ajay@company.com"
    git-commit: "a1b2c3d"
specs:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
      - containerPort: 8080