apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: nginx
      env:
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          value: "mysql-service"
