apiVersion: v1
kind: pod
metadata:
  name: resources-demo
  namespace: expense
spec:
  containers:
    - name: nginx-pod-1
      image: nginx
      resources:
        request:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"