apiVersion: v1
kind: service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    version: 1.0.0
  type: NodePort

---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    app: frontend
spec:
  container:
  - name: nginx-pod-1
    image: nginx
    ports:
    - containerPort: 8080
  