apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app:frontend
  Ports:
  - protocol: TCP
    port: 80               #service port
    targetPort: 100        #container port
    nodePort: 30005
  
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pods
  labels:
    app: frontend
spec:
  containers:
  - name: nginx-pod-1
    image: nginx
    ports:
    - containerPort: 100